### ISSUE TITLE
New crates.io release?

### ISSUE THREAD

**Issue by tomstoneham** [jabedude/procmaps#1]
Hey, thanks so much for writing this crate, super useful to have such a nice library for this :smile: 

I was just wondering, would you be able to publish a release to crates.io which reflects the current state of the repository? I'm able to run `cargo test` on the `master` branch of this repo without issues, but version 0.4.0 on crates.io doesn't have the fixes introduced in commit 728e9f36, and so it won't build on current nightly Rust. I don't think any changes need to be made to the code other than bumping the version.

Thanks again, and have a great day! :heart:

**Comment by jabedude** [comment]
Hey there! Thanks for the nice words, I appreciate them. Doh, sure thing. I must have forgotten to do a new release after pushing that fix

**Comment by jabedude** [comment]
Just uploaded `0.4.1`, tested with the following stable rust version: 

```
stable-x86_64-unknown-linux-gnu (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

**Comment by tomstoneham** [comment]
Great, thanks so much for the quick response :) Have a good one.
